### ISSUE TITLE
What series TV's does this work with?

### ISSUE THREAD

**Issue by ukmoose** [Toxblh/node-red-contrib-samsung-tv-control#1]
Thanks for creating a node for Node-RED.
What series of TV's does this work with?   (Samsung have changed their API several times in recent years).

Could you add to your ReadMe to explain what TV's it works with, and what commands your node supports?

**Comment by Toxblh** [comment]
You are so fast))
Yes, today will do. In short will the same as https://github.com/Toxblh/samsung-tv-control
