### ISSUE TITLE
Disney+ app missing in app list

### ISSUE THREAD

**Issue by increddibelly** [Toxblh/node-red-contrib-samsung-tv-control#11]
Samsung TV Get Apps returns:
`{"appId":"3201901017640","app_type":2,"icon":"/opt/share/webappservice/apps_icon/FirstScreen/3201901017640/250x250.png","is_lock":0,"name":"Disney+"}`
but I can't select Disney+ in the Open App node

could be related to the + sign in the name. 

For completeness, I suggest feeding the dropdown list in the Open App node, by requesting the available apps through the TV Get Apps code.

**Comment by increddibelly** [comment]
I think this PR solves my issue: https://github.com/Toxblh/samsung-tv-control/pull/23 ?

**Comment by increddibelly** [comment]
I hope I got this right. I work in C#, I don't know much about javascript build systems..

**Comment by Toxblh** [comment]
Easy way it's send "3201901017640" in payload to the node OpenApp

**Comment by increddibelly** [comment]
that works, great :-)

**Comment by Dunnenj** [comment]
> Samsung TV Get Apps returns:
> `{"appId":"3201901017640","app_type":2,"icon":"/opt/share/webappservice/apps_icon/FirstScreen/3201901017640/250x250.png","is_lock":0,"name":"Disney+"}`
> but I can't select Disney+ in the Open App node
> 
> could be related to the + sign in the name.
> 
> For completeness, I suggest feeding the dropdown list in the Open App node, by requesting the available apps through the TV Get Apps code.

How did you get that Node working. It does not work for me with a Samsumg the frame (2020). Can you post your flow?

---
John
