### ISSUE TITLE
Every command need permission

### ISSUE THREAD

**Issue by Fr3d3rick83** [Toxblh/node-red-contrib-samsung-tv-control#137]
Hi,
I set up the tv, IP & MAC adress and token but everytime when I enter a command, first I need to accept permission on the tv.

How can I solve this?

**Comment by Just-another-pleb** [comment]
In the spirit of helping...
You need to get a TOKEN from the TV and enter it in the node's config.
The page where you enter the TV's IP address.
This screen:

![Screenshot from 2022-11-15 09-20-51](https://user-images.githubusercontent.com/39888280/201780519-a08075bf-146e-45a6-a693-440f3ad57c16.png)

Then things should work.
Don't worry, the token show has expired for me and doesn't work any more.  But for the sake of showing you where it is.

**Comment by Fr3d3rick83** [comment]
I know this, like I already said, but reinstaling it and pushing the triger after entering the token did the job.

BTW, how can I set the volume to a specific number?

**Comment by Just-another-pleb** [comment]
Hi Fr3d3rick83.
Sorry I don't think it is possible.
It would be nice though.

So is the problem "solved"?  (Yours that is)
And sorry I didn't get your original question.   I answered what I saw as the question.
No it is not unusual to have to accept the token request.   Just so you know.
