### ISSUE TITLE
TV config dialog without MAC

### ISSUE THREAD

**Issue by wbeck77** [Toxblh/node-red-contrib-samsung-tv-control#16]
Hi,

on my system die UI for a new TV looks like this:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/56505039/77901196-7ce4bd80-727f-11ea-94ea-5a1df2a85929.png">

Im using version 1.3.12

Any hints how I can configure the MAC and the production year?

Best regards

Wolfgang Beck

**Comment by Toxblh** [comment]
It's not my plugin 
![image](https://user-images.githubusercontent.com/2198153/77901462-866a2780-7277-11ea-8a70-f5b256b5c5b3.png)
my is https://flows.nodered.org/node/node-red-contrib-samsung-tv-control

**Comment by wbeck77** [comment]
Im using your plugin in version 1.3.12. But the dialog looks different!
<img width="697" alt="image" src="https://user-images.githubusercontent.com/56505039/77912678-4153ee80-7293-11ea-8404-335a8747bf5c.png">

**Comment by Toxblh** [comment]
Yes, but you provide some settings not from my addon. Maybe you have another plugin for samsung tv

**Comment by Toxblh** [comment]
Try to restart NodeRed

**Comment by wbeck77** [comment]
Works! Thank you!
Im wondering why a remove/install cycle of you plugin did not work, but a restart of node-red.... anyway thanks :-)
