### ISSUE TITLE
How to send SmartThings Keys

### ISSUE THREAD

**Issue by Theiamania** [Toxblh/node-red-contrib-samsung-tv-control#17]
Hi,

My Samsung QE55 need to receive the new keys to switch inputs. These keys are here:
https://github.com/ollo69/ha-samsungtv-smart/blob/master/docs/Smartthings.md#smartthings-keys

I test my tv with the ollo69 module and works fine with these new keys. But I prefer to uso node-red instead of Home Assistant.

Can I send "ST_HDMI2" using this nodes? How?

**Comment by Toxblh** [comment]
Hey, my plugin work direct with TV via home network, and for that don't work methods for internet remote connection via SmartThings. Anyway you can send analogue KEY_HDMI2

**Comment by Theiamania** [comment]
Hi Toxblh, my first try was send KEY_HDMI2 but don't works, or any others (KEY_PCMODE, KEY_CUSTOM, KEY_HDMI4, etc) 
"Basic" keys like KEY_PAUSE or KEY_RIGHT works perfectly. 

I don't know how to do something as simple as switching the input.

Any idea will be welcomed!

**Comment by Toxblh** [comment]
Sorry don't know. I just collect information from internet for create the app. Samsung don't open specs API for TV, and don't know app list of KEY's

**Comment by Theiamania** [comment]
Ok. Thank you for your work, Anton.
