### ISSUE TITLE
Missed MAC Address Option in Properties

### ISSUE THREAD

**Issue by ramon2k10** [Toxblh/node-red-contrib-samsung-tv-control#19]
Hi, when I go to config the Samsung Device the Properties form only show me the Name, the IP, and the Token, but this form doesn`t show me me MAC Address Box. I'va the most recent version
of node-red-contrib-samsung-tv-control (1.3.12) and a node-red version v0.20.7

Can you help me, please?

**Comment by Caslinovich** [comment]
Same issue for me, i receive "Error: You must provide MAC in config", but i haven't mac address in config

**Comment by Toxblh** [comment]
Very similar on - please check the issue #16

**Comment by Caslinovich** [comment]
Thanks, resolved with a reboot of nodered. Works like a charm
