### ISSUE TITLE
(More a question)   So what exactly do these nodes allow?

### ISSUE THREAD

**Issue by Just-another-pleb** [Toxblh/node-red-contrib-samsung-tv-control#2]
I have just bought a Samsung TV.   Great!   I'll get this.

Ok....   But now what?

I added a couple of the nodes and one of them tells me if the TV is on or off.

Yeah, Ok.

But then what?

Also, all I had was that node which tells me if the TV is on or off and two debug nodes on the outputs.

NO INPUTS were connected.

Every time I boot the COMPUTER - which has NOTHING to do with the TV - the TV is turned on.
Why?

**Comment by Toxblh** [comment]
> Every time I boot the COMPUTER
WoW. That is bug 😅

So you can send a key
Or open some app

Like my example: 
![image](https://user-images.githubusercontent.com/2198153/72388232-4fc34d00-371d-11ea-8c73-1982ce52c310.png)

First of all, you need to configurate your getToken node. Put IP and Mac, If Tv is on - I think you did here. Next - need to grab a token, for that need to create inject -> getToken -> debug 
Inject it once (click on gray box left of inject node) and open the debug tab, allow notification on TV and copy your token to the setting of the TV. It's all - next time all should work fine.
![image](https://user-images.githubusercontent.com/2198153/72388640-628a5180-371e-11ea-869e-600221bd2f98.png)

**Comment by Toxblh** [comment]
I saw, I fixed it yesterday, please check your version, it should be 1.1.5

**Comment by Just-another-pleb** [comment]
Thanks for the reply.

I shall follow up what you said as soon as I can.

**Comment by Dunnenj** [comment]
> > Every time I boot the COMPUTER
> > WoW. That is bug 😅
> 
> So you can send a key
> Or open some app
> 
> Like my example:
> ![image](https://user-images.githubusercontent.com/2198153/72388232-4fc34d00-371d-11ea-8c73-1982ce52c310.png)
> 
> First of all, you need to configurate your getToken node. Put IP and Mac, If Tv is on - I think you did here. Next - need to grab a token, for that need to create inject -> getToken -> debug
> Inject it once (click on gray box left of inject node) and open the debug tab, allow notification on TV and copy your token to the setting of the TV. It's all - next time all should work fine.
> ![image](https://user-images.githubusercontent.com/2198153/72388640-628a5180-371e-11ea-869e-600221bd2f98.png)

Are you willing to share this flow.

I can use the key commands but are not abble to get the apps. This will help me troubleshooting.
---
John
