### ISSUE TITLE
Names of all the buttons.   Different countries, different signage.

### ISSUE THREAD

**Issue by Just-another-pleb** [Toxblh/node-red-contrib-samsung-tv-control#20]
Maybe for the help of others also, there are some buttons which may vary, country to country.

Using the included/attached picture, could you help identify the buttons?

I know some are obvious.  But some are not.  Rather than guess for any, I may as well ask.

![2020-04-20-103612](https://user-images.githubusercontent.com/39888280/79704247-e80c3780-82f3-11ea-99a1-1660157fa9d4.jpg)

**Comment by Toxblh** [comment]
KEY_SOURCE
KEY_TTX_MIX
KEY_PRECH
Netflix, Amazon Video and WWW only via `openApp`
Exit I didn't find self, but you can use KEY_RETURN instead.
