### ISSUE TITLE
General Question: start youtube video "xyz"

### ISSUE THREAD

**Issue by get-command** [Toxblh/node-red-contrib-samsung-tv-control#22]
Hi,

in advance: thanks for this awesome project!

I don't find any instructions / tutorials , how can i start a youtube video with Title "xyz" direct? is that even possible???

I can start the tv and youtube. this function very well.

**Comment by Toxblh** [comment]
I tried to implement it in main library. But all my tries to try it was fail. But Some guy with old TV said to it's work for him. You can try to do that. If all good, we can to add to node-red

**Comment by get-command** [comment]
thanks. i try it. but i can't send letters to youtube app :-(
