### ISSUE TITLE
Power-Off not working on Q60 model

### ISSUE THREAD

**Issue by tsprivate** [Toxblh/node-red-contrib-samsung-tv-control#3]
Hi,

great work with that node!

I had a few tests with the node and most of it looks good. 

Maybe you can help below:
- I'm not able to "Power-Off" the TV . I used the Key-Send node. Other keys seem to work but not the Power-Off
- I'm not able to get the current state of items like (I know there is no node yet..but would be nice
-- Current Channel
-- Current App
-- Current Volume
-- State Play/Pause

Thanks for considering

**Comment by Toxblh** [comment]
POWEROFF doesn't work on our TVs. 
Use KEY_POWER, it works like a toggle.

I didn't find how to grab the state of TV. Any other action the same like KEY_*Some_action*

**Comment by tsprivate** [comment]
Thanks a lot ... the KEY_POWER did work!

Would be great if we can change directly to a specific TV Channel ;)

**Comment by Toxblh** [comment]
Interesting idea, I’ll try.

**Comment by Toxblh** [comment]
@tsprivate anyway you can use subflows already for that 
![image](https://user-images.githubusercontent.com/2198153/72458095-d92b5b80-37bf-11ea-9460-72d9357423fc.png)

**Comment by tsprivate** [comment]
thats was easy ... I totally did not think of that :( ... that works perfectly with a slight adjustment of the delay timing
