### ISSUE TITLE
Start app does not work UE50NU7090

### ISSUE THREAD

**Issue by increddibelly** [Toxblh/node-red-contrib-samsung-tv-control#4]
I'm trying to start netflix, youtube apps, but that does not seem to do anything.

I have a token. I can send key commands. The TV responds surprisingly quickly to commands. 
![image](https://user-images.githubusercontent.com/3604126/72424334-18d55180-3786-11ea-9af5-c6f4a2c34d16.png)

I can read the app list, but I cannot start any of the apps.
![image](https://user-images.githubusercontent.com/3604126/72424270-ffcca080-3785-11ea-8fd7-7cae84af3285.png)

**Comment by Toxblh** [comment]
I suggest set timeout after turnOn 500ms-3sec, TV can ignore command in the wakeup flow.

**Comment by Toxblh** [comment]
Anyway. Will check

**Comment by increddibelly** [comment]
I'm looking at the web api now - got some details about what's supported and what not on my model:
`{ 
"device":{ 
"FrameTVSupport":"false",
"GamePadSupport":"true",
"ImeSyncedSupport":"true",
"OS":"Tizen",
"TokenAuthSupport":"true",
"VoiceSupport":"false",
"countryCode":"NL",
"description":"Samsung DTV RCR",
"developerIP":"0.0.0.0",
"developerMode":"0",
"duid":"uuid:guid",
"firmwareVersion":"Unknown",
"id":"uuid:guid",
"ip":"samsungtvip",
"model":"18_KANTSU_UHD_BASIC",
"modelName":"UE50NU7090",
"name":"[TV] Samsung TV",
"networkType":"wired",
"resolution":"3840x2160",
"smartHubAgreement":"true",
"type":"Samsung SmartTV",
"udn":"uuid:guid",
"wifiMac":"64:1c:mac:mackity:mac"
},
"id":"uuid:guid",
"isSupport":"{
\"DMP_DRM_PLAYREADY\":\"false\",
\"DMP_DRM_WIDEVINE\":\"false\",
\"DMP_available\":\"true\",
\"EDEN_available\":\"true\",
\"FrameTVSupport\":\"false\",
\"ImeSyncedSupport\":\"true\",
\"TokenAuthSupport\":\"true\",
\"remote_available\":\"true\",
\"remote_fourDirections\":\"true\",
\"remote_touchPad\":\"true\",
\"remote_voiceControl\":\"false\"}\n",
"name":"[TV] Samsung TV",
"remote":"1.0",
"type":"Samsung SmartTV",
"uri":"http://samsungtvip:8001/api/v2/",
"version":"2.0.25"
}`

**Comment by Toxblh** [comment]
As you can see it's all about configuration of tv of features. That just technical information. Maximum that can I use - it provides some information to Node-RED about your TV like a model, resolution, devMode. I think you know that you bought :)
Really useful cases 
1. Check TV is on if the page available, and that how to really work checker of status
2. Rere case for guys who don't read Readme - show warning about, incompatible TV for the plugin.
3. For future switch approach for work with old/new models

**Comment by increddibelly** [comment]
It is working now. I do not understand why. I have sent a couple of left/right button commands and for fun a start app command - and it worked. I guess this should be closed for now until I can find a way to pinpoint a problem. Thank you for your efforts.

**Comment by Dunnenj** [comment]
> I'm trying to start netflix, youtube apps, but that does not seem to do anything.
> 
> I have a token. I can send key commands. The TV responds surprisingly quickly to commands.
> ![image](https://user-images.githubusercontent.com/3604126/72424334-18d55180-3786-11ea-9af5-c6f4a2c34d16.png)
> 
> I can read the app list, but I cannot start any of the apps.
> ![image](https://user-images.githubusercontent.com/3604126/72424270-ffcca080-3785-11ea-8fd7-7cae84af3285.png)

Is it possible to post the flow. That will help me and others.

---
John
