### ISSUE TITLE
Needing help understanding the interaction of the node and the TV

### ISSUE THREAD

**Issue by Just-another-pleb** [Toxblh/node-red-contrib-samsung-tv-control#8]
Sorry, but I'm stuck where else to ask.

I have a *brand new* Samsung TV.
UA43RU7100XXY

When I get to the connection manager of the TV, and look at the list of device, I see the node-red point listed.
When I look at the details it says:   Play Mobile content on TV.   Not Allow control.

Every time I send a command via your node, I get a requestor asking for permission.

I've changed it from "every time" to "first time only" (same result) and even to "don't ask" with also the same result.

Even power cycled the TV.   Same.

It is kind of defeating the purpose if I can't get it working where the computer can send commands and the TV accept them without asking every time.

I "generated a key" as you explained in your previous reply to me.
Yeah, great.   Where do I use it / where do I store it?

I can turn the TV on/off, change channels, adjust volume.   All good, but can't do it without having to "allow" it on the TV.

Yes, that is the other end of the pipe to your node.
But I could still be missing something at the node-red end.

Help appreciated.

**Comment by Toxblh** [comment]
![image](https://user-images.githubusercontent.com/2198153/75610845-ed77ad80-5b0c-11ea-8547-b741fb2c21cc.png)
The token, as I told prev time, need to save in settings of TV, the last field on the screenshot

**Comment by Just-another-pleb** [comment]
Ok, thanks.

But here's the "problem":

Your screen shot is different to what I see.

What node is shown in your example?   It is/was not included in what you say.

This is what I see:

![Screenshot from 2020-03-01 09-11-26](https://user-images.githubusercontent.com/39888280/75615788-c4066280-5b9c-11ea-8a88-9d30cdf51ad9.png)

**Comment by Toxblh** [comment]
Understood.
Pls, click on the button with pencil, right of the "Device" and "Samsung TV" line

**Comment by Just-another-pleb** [comment]
Ah!   Thank you very much.

Seems to be working.

I shall share that with someone else who is also stuck with the same problem

**Comment by Just-another-pleb** [comment]
(Oh, a very quick thought)

Not wanting to *bang on about things*, I had a thought.

Can you make it so, rather than needing "squillions" of nodes for each command, you can have simply ONE node and the {msg.payload} is parsed as the command?

There may be times when that is not possible, but.......

And (sorry) maybe a way to set a volume level.   So rather than send a "volume up" (or down) you can send a "volume x" where x is the value.

Just thinking aloud.

**Comment by Toxblh** [comment]
Yes, I'm thinking about it too about send volume x, and only one way it's possible. 
And it's use SmartThings integration, because Samsung API in local network doesn't reach enough.

About use one combine node and receive all in payload... Interesting the idea :) 
But I follow main guildlines https://nodered.org/docs/creating-nodes/
> be well-defined in their purpose.
> A node that exposes every possible option of an API is potentially less useful that a group of nodes that each serve a single purpose.

Anyway, I think how to do it better in next versions
Thank you for your feedback
